github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

helpers:
  "bin/helper": "github.com/paketo-buildpacks/libjvm/cmd/helper"

codeowners:
  - path: "*"
    owner: "@paketo-buildpacks/java-maintainers"

package:
  repositories: ["docker.io/paketobuildpacks/oracle"]
  register: true
  registry_token: ${{ secrets.PAKETO_BOT_GITHUB_TOKEN }}

docker_credentials:
  - registry: docker.io
    username: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_USERNAME }}
    password: ${{ secrets.PAKETO_BUILDPACKS_DOCKERHUB_PASSWORD }}

dependencies:
  - name: JDK 21
    id: jdk
    version_pattern: "21\\.[\\d]+\\.[\\d]+"
    uses: docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
    with:
      type: jdk
      version: "21"
      distro: oracle
  - name: JDK 25
    id: jdk
    version_pattern: "25\\.[\\d]+\\.[\\d]+"
    uses: docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
    with:
      type: jdk
      version: "25"
      distro: oracle
  - name: Native Image 21
    id: native-image-svm
    version_pattern: "21\\.[\\d]+\\.[\\d]+"
    uses: docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
    with:
      type: jdk
      version: "21"
      distro: graalvm
  - name: Native Image 25
    id: native-image-svm
    version_pattern: "25\\.[\\d]+\\.[\\d]+"
    uses: docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
    with:
      type: jdk
      version: "25"
      distro: graalvm

  # ARM64
  - name: JDK 21 ARM64
    id: jdk
    version_pattern: "21\\.[\\d]+\\.[\\d]+"
    uses: docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
    with:
      type: jdk
      version: "21"
      distro: oracle
      arch: "arm64"
  - name: JDK 25 ARM64
    id: jdk
    version_pattern: "25\\.[\\d]+\\.[\\d]+"
    uses: docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
    with:
      type: jdk
      version: "25"
      distro: oracle
      arch: "arm64"
  - name: Native Image 21 ARM64
    id: native-image-svm
    version_pattern: "21\\.[\\d]+\\.[\\d]+"
    uses: docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
    with:
      type: jdk
      version: "21"
      distro: graalvm
      arch: "arm64"
  - name: Native Image 25 ARM64
    id: native-image-svm
    version_pattern: "25\\.[\\d]+\\.[\\d]+"
    uses: docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
    with:
      type: jdk
      version: "25"
      distro: graalvm
      arch: "arm64"
