github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/oracle
  register:       true
  registry_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- name:            JDK 17
  id:              jdk
  version_pattern: "17\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
  with:
    distro: oracle
    type: jdk
    version: "17"
- name:            JDK 18
  id:              jdk
  version_pattern: "18\\.[\\d]+\\.[\\d]+"
  uses:            docker://ghcr.io/paketo-buildpacks/actions/foojay-dependency:main
  with:
    distro: oracle
    type: jdk
    version: "18"
